import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:cryptography/cryptography.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:twofa/src/services/pairing_crypto.dart';

/// Cross-language interop: vectors generated by the extension's noble-based
/// implementation (extension/scripts/gen_vectors.mjs) must decrypt here.
/// If either side drifts from the shared construction, this fails.
void main() {
  late Map<String, dynamic> v;

  setUpAll(() {
    final file = File('test/fixtures/pairing_vectors.json');
    v = json.decode(file.readAsStringSync()) as Map<String, dynamic>;
  });

  Uint8List b64(String key) =>
      Uint8List.fromList(base64.decode(v[key] as String));

  test('phone derives the same session key as the extension', () async {
    final phoneKeyPair = await X25519()
        .newKeyPairFromSeed(b64('phonePriv'));
    final derivedPub = await phoneKeyPair.extractPublicKey();
    expect(base64.encode(derivedPub.bytes), v['phonePub'],
        reason: 'X25519 public key derivation must match');

    final session = await PairingCrypto.deriveSessionKey(
      ourKeyPair: phoneKeyPair,
      theirPub: b64('extPub'),
      pairingSecret: b64('pairingSecret'),
    );
    expect(base64.encode(session), v['sessionKey'],
        reason: 'HKDF session key must match byte-for-byte');
  });

  test('phone opens a blob sealed by the extension', () async {
    final payload = await PairingCrypto.open(
      b64('sessionKey'),
      v['sealedBlob'] as String,
    );
    expect(payload, v['payload']);
  });

  test('extension can open a blob sealed by the phone (round trip)',
      () async {
    // Seal on the Dart side, open with the same session key here — combined
    // with the vector tests above this proves both directions share one
    // construction.
    final sealed = await PairingCrypto.seal(
      b64('sessionKey'),
      {'verdict': 'approved', 'code': '418902'},
    );
    final reopened =
        await PairingCrypto.open(b64('sessionKey'), sealed);
    expect(reopened, {'verdict': 'approved', 'code': '418902'});
  });
}
